# Робота з бібліотекою Numpy 

In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення. 

In [2]:
array1 = np.arange(1, 21)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення. 

In [3]:
matrix2 = np.ones((4, 4), dtype=int) # dtype=int додала, бо дратували десяткові коми(формат float, що йде за замовченням)
print(matrix2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення. 

In [4]:
matrix3 = np.random.uniform(-1, 1, (5, 5))
print(matrix3)

[[ 0.09204141 -0.38567833 -0.16118653  0.08268818  0.40059882]
 [ 0.39453872  0.06502227  0.04794633 -0.28509716 -0.25384294]
 [-0.5514426   0.83201266 -0.54061178 -0.45528287  0.35083233]
 [ 0.54230403  0.00503365  0.30408956  0.82502457 -0.07026197]
 [ 0.90237481 -0.70048211 -0.61320344  0.55747963 -0.66899994]]


4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення. 

In [5]:
# варіант 1
matrix4_1 = np.random.uniform(0, 1, (3, 3))
print(matrix4_1)

[[0.56098363 0.7581167  0.40756564]
 [0.22483998 0.27276843 0.77909585]
 [0.13890706 0.26764497 0.7813865 ]]


In [6]:
# варіант 2
# np.random.rand за замовчуванням генерує випадкові числа від 0 до 1
matrix4_2 = np.random.rand(3, 3)
print(matrix4_2)

[[0.70094019 0.87464789 0.72922363]
 [0.42331873 0.45073122 0.36050208]
 [0.59516765 0.61043036 0.79749064]]


5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення. 

In [7]:
array5_1 = np.random.randint(1, 21, 6)
array5_2 = np.random.randint(1, 21, 6)

print("Масив 1:", array5_1)
print()
print("Масив 2:", array5_2)

Масив 1: [16  8 12 16 17 14]

Масив 2: [13  1 10 11  3  7]


In [8]:
add_result = array5_1 + array5_2
subtr_result = array5_1 - array5_2
multipl_result = array5_1 * array5_2


print(f"Додавання: {add_result}")
print(f"Віднімання: {subtr_result}")
print(f"Множення: {multipl_result}")

Додавання: [29  9 22 27 20 21]
Віднімання: [ 3  7  2  5 14  7]
Множення: [208   8 120 176  51  98]


6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою. 

In [9]:
matrix6_1 = np.random.randint(1, 6, (3, 2))
matrix6_2 = np.random.randint(1, 6, (2, 4))

print(f"Матриця 1: \n {matrix6_1}")
print()
print(f"Матриця 2: \n {matrix6_2}")

Матриця 1: 
 [[4 5]
 [5 2]
 [4 4]]

Матриця 2: 
 [[4 2 5 1]
 [4 4 2 1]]


In [10]:
multipl_matrix = np.dot(matrix6_1, matrix6_2)

print("Результат перемноження:")
print(multipl_matrix)

Результат перемноження:
[[36 28 30  9]
 [28 18 29  7]
 [32 24 28  8]]


7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її. 

In [11]:
matrix7 = np.random.rand(3, 3)

print("Початкова матриця:")
print(matrix7)

Початкова матриця:
[[0.8666744  0.41258859 0.91832164]
 [0.35458249 0.33785384 0.27579781]
 [0.89692327 0.03571356 0.23844375]]


In [12]:
# варіант 1
transposed_matrix_1 = np.transpose(matrix7)

print("Транспонована матриця:")
print(transposed_matrix_1)

Транспонована матриця:
[[0.8666744  0.35458249 0.89692327]
 [0.41258859 0.33785384 0.03571356]
 [0.91832164 0.27579781 0.23844375]]


In [13]:
# варіант 2
transposed_matrix_2 = matrix7.T
print(transposed_matrix_2)

[[0.8666744  0.35458249 0.89692327]
 [0.41258859 0.33785384 0.03571356]
 [0.91832164 0.27579781 0.23844375]]


8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю. 

In [14]:
matrix8_1 = np.random.randint(1, 11, (3, 3))
matrix8_2 = np.random.randint(1, 11, (3, 3))

print(f"Перша матриця: \n {matrix8_1}")
print()
print(f"Друга матриця: \n {matrix8_2}")

Перша матриця: 
 [[9 6 2]
 [7 4 8]
 [7 6 2]]

Друга матриця: 
 [[3 8 4]
 [7 6 6]
 [8 3 9]]


In [15]:
difference_matrix = matrix8_1 - matrix8_2

print(f"Різниця між матрицями: \n {difference_matrix}")

Різниця між матрицями: 
 [[ 6 -2 -2]
 [ 0 -2  2]
 [-1  3 -7]]


9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток. 

In [16]:
matrix9_1 = np.random.randint(-5, 6, (3, 3))
matrix9_2 = np.random.randint(-5, 6, (3, 3))

print("Перша матриця:")
print(matrix9_1)

print()

print("Друга матриця:")
print(matrix9_2)

Перша матриця:
[[-3  4  4]
 [-1  3 -5]
 [-3 -2  1]]

Друга матриця:
[[ 4 -3 -1]
 [ 3  4  3]
 [-4 -4 -5]]


In [17]:
mult_matrix = np.dot(matrix9_1, matrix9_2)

print("Добуток матриць:")
print(mult_matrix)

Добуток матриць:
[[-16   9  -5]
 [ 25  35  35]
 [-22  -3  -8]]


10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці. 

In [18]:
matrix10 = np.random.uniform(-1, 1, (3, 3))

print("Початкова матриця:")
print(matrix10)

Початкова матриця:
[[ 0.98486936  0.64878333  0.54141576]
 [-0.71147142 -0.22979732  0.52641025]
 [-0.85505775 -0.57392047 -0.18448062]]


In [19]:
row_sums = np.sum(matrix10, axis=1)

print("Вектор-стовпчик сум рядків:")
print(row_sums)

Вектор-стовпчик сум рядків:
[ 2.17506844 -0.41485849 -1.61345884]
